#!/bin/sh
#
# This script is used to run acl test suites
# This script is based on poky's ptest for acl.
#umask 077

testcase_dir=$(realpath ./test)
EXT4_IMAGE=ext4.img
EXT4_MOUNT_POINT=/mnt/ext4

trap 'rm -f ${EXT4_IMAGE}' EXIT

dd if=/dev/zero of=${EXT4_IMAGE} bs=1M count=1
if [ "$?" -eq 0 ]; then
	echo "PASS: dump ext4.img"
else
	echo "FAIL: dump ext4.img"
	exit 1
fi

mkfs.ext4 -F ${EXT4_IMAGE}
if [ "$?" -eq 0 ]; then
	echo "PASS: mkfs.ext4 -F ext4.img"
else
	echo "FAIL: mkfs.ext4 -F ext4.img"
	exit 1
fi

if [ -d $EXT4_MOUNT_POINT ]; then
	echo "mount point exist"
else
	mkdir -p $EXT4_MOUNT_POINT
fi

mount -o loop,rw,acl  ${EXT4_IMAGE} $EXT4_MOUNT_POINT
if [ "$?" -eq 0 ]; then
	echo "PASS: mount ext4.img"
else
	echo "FAIL: mount ext4.img"
	exit 1
fi

cp -rf ./test/ $EXT4_MOUNT_POINT

cd $EXT4_MOUNT_POINT/test/

if [ -e test.group ] && [ -e test.passwd ]; then
	if cp /etc/group group.orig && cp /etc/passwd passwd.orig; then
		cp test.group /etc/group
		cp test.passwd /etc/passwd
		for i in $(find ${testcase_dir} -name "*.test"); do
			${testcase_dir}/run ${i} | sed \
				-e 's|^\[.*\] \(.*\) -- ok$|PASS: \1|' \
				-e 's|^\[.*\] \(.*\) -- failed|FAIL: \1|'
			done
		cp group.orig /etc/group
		cp passwd.orig /etc/passwd
	else
		echo "FAIL: couldn't save original group file or passwd file."
		exit 1
	fi
else
	echo "FAIL: couldn't find group file or passwd file for ptest."
	exit 1
fi

cd -
umount $EXT4_MOUNT_POINT
rm -rf $EXT4_MOUNT_POINT
rm $EXT4_IMAGE
